source 'https://rubygems.org'

gem 'activesupport'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma', require: false
gem 'sinatra', require: 'sinatra/base'
gem 'ulid'
gem 'rack-cache'
gem 'oj'
gem 'oj_mimic_json'

group :development do
  gem 'sinatra-contrib'
  gem 'simplecov'
end
